services:
  caddy:
    image: caddy:2-alpine
    container_name: tributos_proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:
      - DOMAIN=${DOMAIN}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    volumes:
      - ./deploy/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - tributos_network

networks:
  tributos_network:
    external: false

volumes:
  caddy_data:
  caddy_config:
